### ISSUE TITLE
[Wind Turbines] Power Output numbers incorrect?

### ISSUE THREAD

**Issue by VaelophisNyx** [Mrhid6Mods/RRD_Docs#3]
placed one in game (mk2) and I'm at most getting 50Mw?

**Comment by VaelophisNyx** [comment]
additionally the in game description mentions only 100Mw max while the wiki mentions 200?

**Comment by Richard7CE** [comment]
> placed one in game (mk2) and I'm at most getting 50Mw?

Have you disabled wind speed fluctations? ("Use old wind speed (constant)" in mod options)

**Comment by VaelophisNyx** [comment]
Yeah I had

**Comment by Richard7CE** [comment]
There is your problem. This reduces output to half of the maximum.
